# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-21 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='files/{% request.user %}'),
        ),
    ]
