# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-21 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20160521_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to=web.models.user_directory_path),
        ),
    ]
