# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20160521_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistsalbum',
            name='album',
        ),
        migrations.RemoveField(
            model_name='artistsalbum',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='artistssong',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='artistssong',
            name='song',
        ),
        migrations.RemoveField(
            model_name='genresalbum',
            name='album',
        ),
        migrations.RemoveField(
            model_name='genresalbum',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='genresartist',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='genresartist',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='ArtistsAlbum',
        ),
        migrations.DeleteModel(
            name='ArtistsSong',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='GenresAlbum',
        ),
        migrations.DeleteModel(
            name='GenresArtist',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
